project:
  type: website
  output-dir: docs

website:
  title: "Patrick Ballantyne"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research Interests
      - href: publications.qmd
        text: Publications
      - href: Patrick_Ballantyne_CV_A.pdf
        text: CV
      - href: listings.qmd
        text: Blog

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

