---
title: "Research Interests"
---

------------------------------------------------------------------------

## Research Themes

### 1) Retail Geographies, Consumer Behaviour and High Streets

The retail sector continues to face a number of challenges (e.g., online shopping, COVID-19, climate change), putting significant pressure on businesses and retailers to adapt to these challenges. My research in this area explores a number of important ideas:

-   What are the geographies of retail centre agglomerations - where are they located, what characteristics do they have and who uses them?
-   How is the composition and economic performance of retail centres and high streets changing?
-   In what ways is consumer behaviour changing, how can we measure this, and what are the social, economic and environmental consequences of these shifts?

### 2) Spatial Inequality, Accessibility and Place-Based Policy

Spatial inequality is a common phenomena in cities around the world, maintaining cycles of hardship for the most vulnerable members of society. My research in this area aims to unlock new insights about inequalities between places, and support evidence-led policy making to target these. My ongoing research focuses particularly on:

-   The development of digital planning tools (e.g. city dashboards, digital twins) to support place-based policy targeting spatial inequalities.
-   Assembly of urban indicators that summarise the complexity of multidimensional inequalities (e.g. multi-modal transport access and usage) into meaningful and accessible representations.
-   Measurement of place-based inequalities in accessibility to essential services and amenities, utilising new open data from Overture Maps.

------------------------------------------------------------------------

## Research Approach

-   **Methods** - Geographic Information Systems (GIS), Spatial Analysis, Statistical Analysis, Machine Learning, Data Visualisation & Storytelling.

-   **Techniques** - Cluster Analysis (spatial, non-spatial), Network Analysis and Routing, Gravity Models and Catchment Analysis, Predictive Modelling, Dashboard Assembly and Design, Urban Indicator Development, Exploratory Data Analysis.

-   **Data** - Point of Interest (POI), Mobility and Applications-Based, Big Data, Open Data, Secure Data, Census and Administrative.

-   **Workflow** - I work mostly in R. For non-spatial tasks I utilise `tidyverse`, `arrow` and `data.table` to work with datasets ranging from small to large, and then for spatial tasks I rely heavily on the `sf` library for spatial operations. I have lots of experience in building docker instances on HPC infrastructure, and regularly use such infrastructure for larger tasks.
